### PR TITLE
Add tuple indexing operator

### PR DESCRIPTION
**Pull request by segeljakt**
Adds indexing operator for tuples which takes a constant attribute as index. Also adds tests for the following:

* Out of bounds index (greater than the tuple size).
* Negative index.
* No index specified.
* Indexed element type does not match the expected result type.
* True negative test.

### CODE REVIEW

**Comment by segeljakt** [comment]
I did not manage to get the [`Index`-type](https://github.com/llvm/llvm-project/blob/308571074c13ea2a0758aa085aa02f72150f891e/mlir/include/mlir/IR/OpBase.td#L315) working, but maybe it is not necessary for Tuples anyway

**Comment by frej** [comment]
This one has broken the mlir branch. I know that you don't really want to have to compile the debug version of LLVM, but you really have to check with assertions enabled. You want LLVM_ENABLE_ASSERTIONS=ON even if you build the release version.

```
FAIL: ARC-MLIR :: invalid-index-tuple-out-of-bounds.mlir (18 of 21)
******************** TEST 'ARC-MLIR :: invalid-index-tuple-out-of-bounds.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /var/scratch-1/arcon/build/llvm-build/bin/arc-mlir /var/tmp/arcon/arc/arc-mlir/src/tests/invalid-index-tuple-out-of-bounds.mlir -split-input-file -verify-diagnostics
--
Exit Code: 134

Command Output (stderr):
--
arc-mlir: /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:250: const T &llvm::ArrayRef<mlir::Type>::operator[](size_t) const [T = mlir::Type]: Assertion `Index < Length && "Invalid index!"' failed.
Stack dump:
0.      Program arguments: /var/scratch-1/arcon/build/llvm-build/bin/arc-mlir /var/tmp/arcon/arc/arc-mlir/src/tests/invalid-index-tuple-out-of-bounds.mlir -split-input-file -verify-diagnostics 
 #0 0x0000000000e216a7 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/lib/Support/Unix/Signals.inc:564:11
 #1 0x0000000000e21849 PrintStackTraceSignalHandler(void*) /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/lib/Support/Unix/Signals.inc:625:1
 #2 0x0000000000e2005b llvm::sys::RunSignalHandlers() /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/lib/Support/Signals.cpp:67:5
 #3 0x0000000000e21fc5 SignalHandler(int) /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/lib/Support/Unix/Signals.inc:406:1
 #4 0x00007faa53551500 __restore_rt (/lib64/libpthread.so.0+0x14500)
 #5 0x00007faa52f70c71 raise (/lib64/libc.so.6+0x38c71)
 #6 0x00007faa52f5a535 abort (/lib64/libc.so.6+0x22535)
 #7 0x00007faa52f5a40f (/lib64/libc.so.6+0x2240f)
 #8 0x00007faa52f68772 (/lib64/libc.so.6+0x30772)
 #9 0x000000000059ae59 llvm::ArrayRef<mlir::Type>::operator[](unsigned long) const /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:0:7
#10 0x0000000000d11cb6 arc::IndexTuple::verify() /var/scratch-1/arcon/build/llvm-build/tools/arc-mlir/include/arc/ops.cpp.inc:867:20
#11 0x0000000000d1cd53 mlir::Op<arc::IndexTuple, mlir::OpTrait::OneResult, mlir::OpTrait::HasNoSideEffect, mlir::OpTrait::OneOperand>::verifyInvariants(mlir::Operation*) /var/tmp/arcon/arc/arc-mlir/src/../llvm-project/mlir/include/mlir/IR/OpDefinition.h:1019:39
#12 0x00000000004ce395 (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:188:24
#13 0x00000000004cedef (anonymous namespace)::OperationVerifier::verifyBlock(mlir::Block&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:147:16
#14 0x00000000004ceadb (anonymous namespace)::OperationVerifier::verifyRegion(mlir::Region&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:126:16
#15 0x00000000004ce451 (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:193:16
#16 0x00000000004cedef (anonymous namespace)::OperationVerifier::verifyBlock(mlir::Block&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:147:16
#17 0x00000000004ceadb (anonymous namespace)::OperationVerifier::verifyRegion(mlir::Region&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:126:16
#18 0x00000000004ce451 (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:193:16
#19 0x00000000004cde8a (anonymous namespace)::OperationVerifier::verify(mlir::Operation&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:97:14
#20 0x00000000004cddce mlir::verify(mlir::Operation*) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Analysis/Verifier.cpp:265:46
#21 0x00000000006f18cc mlir::parseSourceFile(llvm::SourceMgr const&, mlir::MLIRContext*) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Parser/Parser.cpp:4776:14
#22 0x00000000006ed59a performActions(llvm::raw_ostream&, bool, bool, llvm::SourceMgr&, mlir::MLIRContext*, mlir::PassPipelineCLParser const&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Support/MlirOptMain.cpp:45:8
#23 0x00000000006ed512 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, bool, bool, mlir::PassPipelineCLParser const&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Support/MlirOptMain.cpp:91:3
#24 0x00000000006ed801 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::PassPipelineCLParser const&, bool, bool, bool)::$_0::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) const /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Support/MlirOptMain.cpp:110:18
#25 0x00000000006ed775 mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::PassPipelineCLParser const&, bool, bool, bool)::$_0>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/include/llvm/ADT/STLExtras.h:108:12
#26 0x0000000000c9fa41 llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&)>::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) const /var/tmp/arcon/arc/arc-mlir/llvm-project/llvm/include/llvm/ADT/STLExtras.h:125:12
#27 0x0000000000c9f921 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&)>, llvm::raw_ostream&) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Support/ToolUtilities.cpp:42:16
#28 0x00000000006ed337 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, mlir::PassPipelineCLParser const&, bool, bool, bool) /var/tmp/arcon/arc/arc-mlir/llvm-project/mlir/lib/Support/MlirOptMain.cpp:107:12
#29 0x0000000000d0b2c1 main /var/tmp/arcon/arc/arc-mlir/src/main.cpp:99:17
#30 0x00007faa52f5bf1b __libc_start_main (/lib64/libc.so.6+0x23f1b)
#31 0x000000000040e21a _start (/var/scratch-1/arcon/build/llvm-build/bin/arc-mlir+0x40e21a)
/var/scratch-1/arcon/build/llvm-build/tools/arc-mlir/tests/test/Output/invalid-index-tuple-out-of-bounds.mlir.script: line 1: 28020 Aborted                 /var/scratch-1/arcon/build/llvm-build/bin/arc-mlir /var/tmp/arcon/arc/arc-mlir/src/tests/invalid-index-tuple-out-of-bounds.mlir -split-input-file -verify-diagnostics

```

**Comment by segeljakt** [comment]
Oh, I mistakenly thought we had them enabled by default, but now I see I need to
```bash
A2M_ASSERTS=1 BUILD_FLAVOUR=MinSizeRel ./arc-mlir-build
```

**Comment by segeljakt** [comment]
@frej woops, I mistakenly thought we had them enabled by default, but now I see I need to
```bash
A2M_ASSERTS=1 BUILD_FLAVOUR=MinSizeRel ./arc-mlir-build
```

**Pull request merged**
