### PR TITLE
arc script mlir fixes

### PR DESCRIPTION
**Pull request by frej**
* Lower math.powf properly
* Output NaNs and +/- inf correctly
* Run insta/src/expect-pass/binops.arc with arc-to-rust

### CODE REVIEW

**Comment by segeljakt** [comment]
LGTM, looks like you found a bug in arc-script with `pow`. I can address it in a PR.

**Comment by frej** [comment]
> LGTM, looks like you found a bug in arc-script with `pow`. I can address it in a PR.

Are you sure, I thought it was that you have to use `powf`/`powi` depending on the type?

**Comment by segeljakt** [comment]
>Are you sure, I thought it was that you have to use powf/powi depending on the type? I thought it was just a bug in the MLIR backend, why didn't it fail before?

I have not yet added so the tests check the generated code but I probably should :eyes:

**Review by segeljakt — APPROVED** [review]
LGTM

**Pull request merged**
